////////////////////////////**********************************PRUEBAS PARA ETL Y DW *********************************////////////////////////////////////////
USE IF6201_DW_STORE_B82444
--SELECT * FROM DW.DIM_HECHOS_STORE
SELECT COUNT(*) FROM DW.DIM_HECHOS_STORE
USE IF6201_EX2_Aplicada_B82444
--SELECT * FROM SALE_DETAIL
SELECT COUNT(*) FROM SALE_DETAIL

USE IF6201_EX2_Aplicada_B82444
SELECT * FROM SALE_DETAIL
USE IF6201_EX2_Aplicada_B82444
SELECT * FROM SALE
USE IF6201_EX2_Aplicada_B82444
SELECT * FROM PRODUCT
USE IF6201_EX2_Aplicada_B82444
SELECT * FROM CUSTOMER

USE IF6201_DW_STORE_B82444
SELECT * FROM DW.DIM_HECHOS_STORE
SELECT * FROM DW.DIM_CUSTOMER
SELECT * FROM DW.DIM_TIME
////////////////////////////************************************************************************************////////////////////////////////////////

DATOS (MOCKAROO)

insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Charles Gorioli', 47, 'cgorioli0@auda.org.au', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kristine Lummus', 32, 'klummus1@icq.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Minda Bursnell', 27, 'mbursnell2@mediafire.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Willi Thickpenny', 66, 'wthickpenny3@blogs.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sherilyn Gatiss', 22, 'sgatiss4@usnews.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Aube Forrest', 29, 'aforrest5@purevolume.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Brose Longfield', 27, 'blongfield6@creativecommons.org', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mellie Batch', 58, 'mbatch7@aboutads.info', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Joline Swendell', 43, 'jswendell8@amazon.co.uk', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ellissa Grattan', 33, 'egrattan9@sourceforge.net', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Micki Loidl', 53, 'mloidla@sogou.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Millisent Parsall', 56, 'mparsallb@springer.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Charisse Brudenell', 26, 'cbrudenellc@purevolume.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kingsley Taffurelli', 42, 'ktaffurellid@ifeng.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gustav De Blasiis', 38, 'gdee@imageshack.us', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Patten Currall', 34, 'pcurrallf@cafepress.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Salomo Cubbin', 59, 'scubbing@accuweather.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kipper Rillatt', 55, 'krillatth@nhs.uk', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Angeline Gellately', 64, 'agellatelyi@slate.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lil Nichols', 39, 'lnicholsj@biblegateway.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Emmalynne Bascomb', 31, 'ebascombk@adobe.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ardith Joplin', 36, 'ajoplinl@netscape.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Anjanette Banbrigge', 24, 'abanbriggem@dyndns.org', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bennett Halsall', 25, 'bhalsalln@shinystat.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Edi Barfitt', 37, 'ebarfitto@apache.org', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cello Alabaster', 48, 'calabasterp@dell.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jaymie Camilli', 20, 'jcamilliq@ihg.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Fawne Rimell', 30, 'frimellr@163.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Nerita Rogier', 37, 'nrogiers@constantcontact.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Edeline Fuke', 62, 'efuket@ameblo.jp', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Robbie Howle', 27, 'rhowleu@ca.gov', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Teodorico Osgorby', 46, 'tosgorbyv@comcast.net', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Parke Teodori', 70, 'pteodoriw@bluehost.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Leila Garaghan', 33, 'lgaraghanx@wired.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Shoshana Siveter', 19, 'ssivetery@elegantthemes.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Susanetta Ascroft', 74, 'sascroftz@reddit.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ernaline Cotta', 60, 'ecotta10@ehow.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jorgan Poston', 65, 'jposton11@blogtalkradio.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mersey Delcastel', 73, 'mdelcastel12@marketwatch.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rodd Blackaller', 54, 'rblackaller13@foxnews.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Alex Dayment', 34, 'adayment14@rakuten.co.jp', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Corbie Thirlwell', 35, 'cthirlwell15@soundcloud.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Moselle Cleghorn', 18, 'mcleghorn16@simplemachines.org', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Saxon Nelthropp', 36, 'snelthropp17@merriam-webster.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Damiano Irlam', 61, 'dirlam18@unc.edu', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cly Horlick', 30, 'chorlick19@github.io', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Elena Noye', 27, 'enoye1a@4shared.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Torrey McAdam', 32, 'tmcadam1b@soup.io', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ellswerth Vevers', 66, 'evevers1c@tiny.cc', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Yvor Nowakowska', 50, 'ynowakowska1d@biblegateway.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ranice Storck', 69, 'rstorck1e@netlog.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Frannie Fidian', 53, 'ffidian1f@com.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ketti Hasty', 27, 'khasty1g@shutterfly.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Denice Codi', 65, 'dcodi1h@twitter.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gloriane Geraghty', 19, 'ggeraghty1i@github.io', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Orel Fold', 41, 'ofold1j@samsung.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Annmaria Rosengart', 68, 'arosengart1k@arstechnica.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Felice Snoding', 73, 'fsnoding1l@kickstarter.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Val Nesbitt', 57, 'vnesbitt1m@mail.ru', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Netty Bowich', 59, 'nbowich1n@yelp.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Almire Eldershaw', 42, 'aeldershaw1o@imgur.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Itch Defau', 49, 'idefau1p@angelfire.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Emmerich Yandle', 75, 'eyandle1q@seattletimes.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lucias Ellingham', 67, 'lellingham1r@ibm.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dunn Cazalet', 18, 'dcazalet1s@mtv.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bartlet Harrod', 48, 'bharrod1t@cpanel.net', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ximenes Siggens', 72, 'xsiggens1u@newsvine.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ginevra Ohrtmann', 53, 'gohrtmann1v@statcounter.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Thedric Gertray', 62, 'tgertray1w@hexun.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cleon Garriock', 45, 'cgarriock1x@nationalgeographic.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Tiertza Lebrun', 59, 'tlebrun1y@seattletimes.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sosanna Trewhitt', 24, 'strewhitt1z@tinypic.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Eal Tschersich', 41, 'etschersich20@xrea.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bea Coggill', 56, 'bcoggill21@cdbaby.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sada Aspy', 32, 'saspy22@psu.edu', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Valle Spraberry', 48, 'vspraberry23@theglobeandmail.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Denis Cluet', 58, 'dcluet24@state.tx.us', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kassandra Illingworth', 19, 'killingworth25@ning.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Orion Arsmith', 27, 'oarsmith26@domainmarket.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Doralyn Ridder', 48, 'dridder27@shareasale.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Steven Boyle', 74, 'sboyle28@issuu.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Tish Cubbin', 35, 'tcubbin29@google.cn', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Horace Talton', 39, 'htalton2a@thetimes.co.uk', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Earl Lorkins', 56, 'elorkins2b@npr.org', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lancelot Jozsa', 45, 'ljozsa2c@addtoany.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Neddy Nono', 57, 'nnono2d@kickstarter.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Zorina Blinkhorn', 50, 'zblinkhorn2e@indiegogo.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Nehemiah Tuckett', 55, 'ntuckett2f@themeforest.net', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Celeste Rhymer', 63, 'crhymer2g@slideshare.net', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Beatrice Haggarty', 72, 'bhaggarty2h@google.ca', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Loni Colles', 50, 'lcolles2i@independent.co.uk', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Christopher Shadfourth', 54, 'cshadfourth2j@paypal.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Margy McCaughan', 49, 'mmccaughan2k@shutterfly.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Toinette Kilbey', 59, 'tkilbey2l@newyorker.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Keely Ruddin', 28, 'kruddin2m@army.mil', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gradey Laible', 38, 'glaible2n@sitemeter.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mill Extance', 46, 'mextance2o@drupal.org', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rodrique Stammler', 34, 'rstammler2p@webnode.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Darci Cartan', 21, 'dcartan2q@wunderground.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Berry Addey', 46, 'baddey2r@engadget.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mac Saltmarshe', 68, 'msaltmarshe2s@buzzfeed.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Edee Hurburt', 50, 'ehurburt2t@uiuc.edu', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gaven Vatcher', 43, 'gvatcher2u@unicef.org', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Shelton Quarterman', 60, 'squarterman2v@marketwatch.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Vachel McKeeman', 44, 'vmckeeman2w@state.tx.us', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lyndsey Broadstock', 26, 'lbroadstock2x@utexas.edu', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ketty Eckersall', 73, 'keckersall2y@nasa.gov', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Toni Avraam', 65, 'tavraam2z@mlb.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kaitlynn Anshell', 34, 'kanshell30@php.net', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ernest Mowat', 45, 'emowat31@people.com.cn', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Anne-marie Du Hamel', 57, 'adu32@tripod.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mariellen Presland', 45, 'mpresland33@google.ru', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Alyce Playford', 26, 'aplayford34@bigcartel.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Thorin Rumke', 23, 'trumke35@bandcamp.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Worden Corstan', 39, 'wcorstan36@cdbaby.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ruby Jakolevitch', 18, 'rjakolevitch37@4shared.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Avictor Tampling', 59, 'atampling38@deviantart.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Conchita Bibbie', 38, 'cbibbie39@economist.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lezlie Robinet', 19, 'lrobinet3a@indiegogo.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ado Addison', 28, 'aaddison3b@businessweek.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Allx Daddow', 31, 'adaddow3c@reuters.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Wait Puddicombe', 40, 'wpuddicombe3d@reference.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Wenona Jory', 35, 'wjory3e@google.ru', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Curt Killigrew', 29, 'ckilligrew3f@kickstarter.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lalo Bollins', 21, 'lbollins3g@a8.net', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Anatole Albone', 27, 'aalbone3h@privacy.gov.au', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Janelle Coste', 40, 'jcoste3i@hhs.gov', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Joyous Pringuer', 27, 'jpringuer3j@ft.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mariya Dumbreck', 31, 'mdumbreck3k@goodreads.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Alisun Crawley', 29, 'acrawley3l@ihg.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Pascale Maudsley', 34, 'pmaudsley3m@yale.edu', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gustav Blindt', 64, 'gblindt3n@amazon.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Graeme Dumpleton', 36, 'gdumpleton3o@apache.org', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Elise Spedding', 50, 'espedding3p@nifty.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rupert Bampforth', 63, 'rbampforth3q@oakley.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Fawnia Thynne', 74, 'fthynne3r@forbes.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Marcus Scupham', 58, 'mscupham3s@nasa.gov', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Magda Breddy', 62, 'mbreddy3t@yolasite.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Modestia Elmhirst', 29, 'melmhirst3u@stanford.edu', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Spence Danford', 46, 'sdanford3v@hibu.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cloris Milne', 74, 'cmilne3w@eventbrite.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Karleen Reide', 48, 'kreide3x@irs.gov', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Gris Hallut', 48, 'ghallut3y@4shared.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Albert MacNally', 23, 'amacnally3z@geocities.jp', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mallory Geeves', 59, 'mgeeves40@stanford.edu', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Leonanie Surman', 70, 'lsurman41@sohu.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Malvin Trustram', 59, 'mtrustram42@usatoday.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Doy Engley', 41, 'dengley43@angelfire.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mag Overy', 72, 'movery44@umn.edu', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Abigale Pilbury', 64, 'apilbury45@earthlink.net', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jocko Sibery', 41, 'jsibery46@businessinsider.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Drud Downes', 46, 'ddownes47@storify.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Lorena Hauch', 57, 'lhauch48@friendfeed.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jamie Padbury', 46, 'jpadbury49@1688.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Grace Tree', 33, 'gtree4a@posterous.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Corrie Pimm', 24, 'cpimm4b@si.edu', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bengt Cutriss', 55, 'bcutriss4c@umich.edu', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Beryle Rippon', 55, 'brippon4d@vinaora.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Marya Deason', 34, 'mdeason4e@ask.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Blythe Cornick', 67, 'bcornick4f@bloglovin.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Addison Crix', 41, 'acrix4g@typepad.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dill Eade', 22, 'deade4h@biglobe.ne.jp', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Darrick Duddan', 25, 'dduddan4i@nature.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jelene Iddins', 44, 'jiddins4j@nih.gov', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Denys Heaslip', 62, 'dheaslip4k@merriam-webster.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dana Phare', 39, 'dphare4l@hc360.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bendite Shawley', 18, 'bshawley4m@google.com.hk', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Burl Werrit', 70, 'bwerrit4n@bluehost.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Clea Barge', 55, 'cbarge4o@networkadvertising.org', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Karyn Mothersole', 70, 'kmothersole4p@tripadvisor.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Archer Stearn', 74, 'astearn4q@hud.gov', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Madlen Elmhirst', 24, 'melmhirst4r@bloglovin.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Anstice Boat', 38, 'aboat4s@wordpress.org', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rolando Gersam', 34, 'rgersam4t@webmd.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rudy Adderley', 46, 'radderley4u@digg.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bourke Vaen', 37, 'bvaen4v@ca.gov', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Tanney Nobbs', 23, 'tnobbs4w@dailymotion.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Janessa Epine', 49, 'jepine4x@seesaa.net', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Marita McGragh', 28, 'mmcgragh4y@typepad.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dimitri Brodley', 33, 'dbrodley4z@hostgator.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Darryl Jorden', 31, 'djorden50@sciencedaily.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Janifer Chasson', 51, 'jchasson51@booking.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Maritsa Tall', 25, 'mtall52@twitpic.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Alissa Turfitt', 39, 'aturfitt53@techcrunch.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Aurthur Vaissiere', 34, 'avaissiere54@cyberchimps.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Garrik Pietsma', 54, 'gpietsma55@usnews.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Johnath Braybrooks', 45, 'jbraybrooks56@dropbox.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Nathalia Banger', 52, 'nbanger57@sciencedaily.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Callean Joly', 63, 'cjoly58@wikia.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Travers Renackowna', 28, 'trenackowna59@zimbio.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Wain Kleimt', 74, 'wkleimt5a@dropbox.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Bail Blenkinship', 58, 'bblenkinship5b@etsy.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sherilyn Tatchell', 18, 'statchell5c@google.de', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Phineas Cuthill', 60, 'pcuthill5d@simplemachines.org', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Muffin Venditti', 19, 'mvenditti5e@friendfeed.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Antonio Denson', 33, 'adenson5f@japanpost.jp', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Tobe Esposi', 58, 'tesposi5g@ft.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kimmie Pryer', 20, 'kpryer5h@who.int', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Maressa Cardenoza', 52, 'mcardenoza5i@nyu.edu', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Christiane Breinl', 46, 'cbreinl5j@blogger.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Nathalia Cardenosa', 70, 'ncardenosa5k@home.pl', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dagmar Newbury', 63, 'dnewbury5l@usda.gov', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ermina Instock', 24, 'einstock5m@alexa.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Moreen O''Cleary', 20, 'mocleary5n@paginegialle.it', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Haslett Sevin', 32, 'hsevin5o@cocolog-nifty.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mitchael Pinkstone', 62, 'mpinkstone5p@ow.ly', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ashlie Pentecust', 58, 'apentecust5q@arizona.edu', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Krisha Wassung', 62, 'kwassung5r@jimdo.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jerome Richardon', 69, 'jrichardon5s@usgs.gov', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Marylinda Behrendsen', 38, 'mbehrendsen5t@youtube.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Denver Hews', 57, 'dhews5u@webnode.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Corrie Dewsnap', 52, 'cdewsnap5v@ustream.tv', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Arni Reinisch', 69, 'areinisch5w@yandex.ru', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Beverlie Sutor', 32, 'bsutor5x@nymag.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Maritsa Burdekin', 25, 'mburdekin5y@wix.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mendie Martignon', 21, 'mmartignon5z@blogtalkradio.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ewen Ewles', 29, 'eewles60@domainmarket.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Conchita Karpets', 33, 'ckarpets61@furl.net', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Anna-diane Darrel', 65, 'adarrel62@163.com', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Haze Whaymand', 48, 'hwhaymand63@blinklist.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Clementine Goodredge', 59, 'cgoodredge64@arstechnica.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sallyanne Rawlings', 32, 'srawlings65@phpbb.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Aleda Klimek', 62, 'aklimek66@bizjournals.com', 'Nicaragua');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mikkel Bradneck', 58, 'mbradneck67@reference.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Elinor Semerad', 56, 'esemerad68@domainmarket.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cathe Currao', 55, 'ccurrao69@gnu.org', 'Chile');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Skipper Hext', 64, 'shext6a@pinterest.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dory Farron', 66, 'dfarron6b@hibu.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Enrico McElrath', 65, 'emcelrath6c@github.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Wainwright Carpmile', 52, 'wcarpmile6d@samsung.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Odey Kilgrove', 23, 'okilgrove6e@ox.ac.uk', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Estrella Brimmacombe', 62, 'ebrimmacombe6f@multiply.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Amos Scedall', 66, 'ascedall6g@tmall.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Nels Scutching', 31, 'nscutching6h@google.ca', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Dacy Mothersole', 19, 'dmothersole6i@gizmodo.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Conney Gorler', 63, 'cgorler6j@canalblog.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Sybil Sketchley', 61, 'ssketchley6k@yahoo.co.jp', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Rafaelita Winborn', 51, 'rwinborn6l@so-net.ne.jp', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Mora Caisley', 73, 'mcaisley6m@google.ca', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Kennedy Persitt', 41, 'kpersitt6n@yelp.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Roderic Quiddington', 22, 'rquiddington6o@smh.com.au', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Annabal Denisyev', 54, 'adenisyev6p@wiley.com', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Jehanna Stanger', 27, 'jstanger6q@github.com', 'Costa Rica');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Wendall Marzelli', 32, 'wmarzelli6r@globo.com', 'Honduras');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Cullen Mackieson', 72, 'cmackieson6s@msn.com', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Electra Wrightson', 64, 'ewrightson6t@vk.com', 'Panama');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Ogdan Casari', 67, 'ocasari6u@webmd.com', 'El Salvador');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Marika Antonignetti', 73, 'mantonignetti6v@dailymail.co.uk', 'Guatemala');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Freemon Tuttle', 68, 'ftuttle6w@last.fm', 'Mexico');
insert into CUSTOMER (FULLNAME, AGE, EMAIL, COUNTRY) values ('Melloney Fitzsimmons', 29, 'mfitzsimmons6x@go.com', 'Chile');





insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Aluminio', 2000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tuerca', 1500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tornillo', 2500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Martillo', 1500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tuerca', 500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Zinc', 1500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Ladrillo', 800);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Varillas', 400);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Clavos', 1000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Taladro', 2000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Brocas', 9000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Madera', 6000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tablas', 4610);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cemeno', 2500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Destornillador', 2000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cables', 3210);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Meazcladora', 300000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Rodillo', 3500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pintura', 10500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pintura Roja', 10500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pintura Verde', 10500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pintura Blanca', 10500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pintura Gris', 10500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Ceramica porcelanato', 30500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Bombillo', 1200);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tubo pbc', 1900);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Tablilla', 3500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Alicate', 2100);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cincel', 2605);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Pinzas', 6200);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Prensas', 5000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Remachadoras', 12500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Niveles', 4500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Torquimetros', 1750);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Escalera', 28500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cutter', 2300);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Odometro', 25000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cortatubos', 20000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Espatula', 1000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cautin', 3200);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Barreta de una', 6500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Flexometro', 4000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Desarmador', 1500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Cizalla', 3000);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('LLave Hexagonal', 2500);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Desforradora', 4300);
insert into PRODUCT(NAME_PRODUCT, PRICE) values ('Dado MM', 3150);
