CREATE DATABASE IF6201_EX2_Aplicada_B82444
GO
CREATE TABLE CUSTOMER (
	ID_CUSTOMER int IDENTITY(1,1) NOT NULL,
	FULLNAME varchar(150) NOT NULL,
	AGE int NOT NULL,
	COUNTRY VARCHAR(120)NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
CONSTRAINT PK_CUSTOMER PRIMARY KEY(ID_CUSTOMER)
)

CREATE TABLE SALE (
	ID_SALE int IDENTITY(1,1) NOT NULL,
	ID_CUSTOMER int NOT NULL,
	BILL_DATE DATETIME NOT NULL,
CONSTRAINT PK_SALE PRIMARY KEY
(
	ID_SALE
),
CONSTRAINT FK_SALE_CUSTOMER_SALE FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER)
)

CREATE TABLE PRODUCT (
	ID_PRODUCT int IDENTITY(1,1) NOT NULL,
	NAME_PRODUCT varchar(150) NOT NULL,
	PRICE int NOT NULL,
CONSTRAINT PK_PRODUCT PRIMARY KEY(ID_PRODUCT)
)

CREATE TABLE SALE_DETAIL (
	ID_SALE_DETAIL int IDENTITY(1,1) NOT NULL,
	ID_PRODUCT int NOT NULL,
	ID_SALE int NOT NULL,
	QUANTITY INT NOT NULL,
	AMOUNT INT NOT NULL
CONSTRAINT PK_SALE_DETAIL PRIMARY KEY
(
	ID_SALE_DETAIL,
	ID_PRODUCT,
	ID_SALE
),
CONSTRAINT FK_SALE_DETAIL_SALE FOREIGN KEY (ID_SALE) REFERENCES SALE (ID_SALE),
CONSTRAINT FK_SALE_DETAIL_PRODUCT FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT (ID_PRODUCT)
)